kursach-master/config/routes.rb
Rails.application.routes.draw do
  resources :themes
  root 'sites#new'
  get 'persons/profile', as: 'user_root'
  resources :sites
  resources :menus
  resources :temps

end

kursach-master/app/models/site.rb
class Site < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true
  validates :description, :tags, :logo_url, presence: true
  belongs_to :temp
  belongs_to :menu
  belongs_to :theme
end

kursach-master/app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:title, :description, :tags, :logo_url, :temp_id, :menu_id)
    end
end

kursach-master/app/helpers/sites_helper.rb
module SitesHelper
end

kursach-master/app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_area :tags %>
  </div>
  <div class="field">
    <%= f.label :logo_url %><br>
    <%= f.text_field :logo_url %>
  </div>
    <div class="field">
      <%= f.label :temp_id %><br>
      <% Temp.all.each do |temp| %>
          <%= f.radio_button :temp_id, temp.id %>
          <%= image_tag temp.temp_image, style: 'width: 10%; height: 10%;' %>
      <% end %>
    </div>
    <div class="field">
      <%= f.label :menu_id %><br>
      <% Menu.all.each do |menu| %>
          <%= f.radio_button :menu_id, menu.id %>
          <%= image_tag menu.menu_image, style: 'width: 10%; height: 10%;'%>
      <% end %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

kursach-master/app/views/sites/edit.html.erb
<h1>Editing Site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

kursach-master/app/views/sites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sites</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Tags</th>
      <th>Logo url</th>
      <th>Temp</th>
      <th>Menu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= site.title %></td>
        <td><%= site.description %></td>
        <td><%= site.tags %></td>
        <td><%= site.logo_url %></td>
        <td><%= site.temp %></td>
        <td><%= site.menu %></td>
        <td><%= link_to 'Show', site %></td>
        <td><%= link_to 'Edit', edit_site_path(site) %></td>
        <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site', new_site_path %>

kursach-master/app/views/sites/new.html.erb
<h1>New Site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

kursach-master/app/views/sites/show.html.erb
<!DOCTYPE HTML>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="bootstrap.min.css" rel="stylesheet">
  <link href="Menu.css" rel="stylesheet">
  <link href="font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" href="../font-awesome-4.6.1/css/font-awesome.min.css">

  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>
  <p id="notice"><%= notice %></p>


  <script src="jquery-3.0.0.min.js"></script>
  <script src="bootstrap.min.js"></script>
  <script type="text/javascript" charset="utf-8" src="Menu.js"></script>
  <title>Menu</title>
</head>

<body>


<p>
  <strong>Description:</strong>
  <%= @site.description %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @site.tags %>
</p>
<p>
  <strong>Logo url:</strong>
  <%= @site.logo_url %>
</p>


<p>
  <strong>Menu:</strong>
  <%= @site.menu_id %>
</p>

<i class="fa fa-facebook"></i>
<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>

<% if @site.temp_id == 1 %>
    <div class="wrapper">

      <header class="header">
        <%= @site.title %>
      </header><!-- .header-->

      <main class="content">

      </main><!-- .content -->

    </div><!-- .wrapper -->

    <footer class="footer">

    </footer><!-- .footer -->

<!-- MENU -->
<nav class="menu" id="theMenu">
  <div class="menu-wrap">
    <h1 class="logo"><a href="homepage.html#home">up</a></h1>
    <a href="services.html">Services</a>
    <a href="portfolio.html">Portfolio</a>
    <a href="about.html">About</a>
    <a href="#contact">Contact</a>
    <a href="https://www.facebook.com/sashka.osipov" target="_blank"><i class="fa fa-facebook"></i></a>
    <a href="https://twitter.com/Fusionmeow" target="_blank"><i class="fa fa-twitter"></i></a>
    <a href="https://vk.com/fusionqq" target="_blank"><i class="fa fa-vk"></i></a>
    <a href="https://www.instagram.com/alexadrias" target="_blank"><i class="fa fa-instagram"></i></a>
  </div>

  <!-- Menu button -->
  <div id="menuToggle"><i class="fa fa-bars"></i></div>
</nav>




<% end %>
</body>
</html>