kursach-master/config/routes.rb
Rails.application.routes.draw do
  resources :themes
  root 'sites#new'
  get 'persons/profile', as: 'user_root'
  resources :sites
  resources :menus
  resources :temps

end

kursach-master/app/models/theme.rb
class Theme < ActiveRecord::Base
  has_many :sites
end

kursach-master/app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  # GET /themes
  # GET /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: 'Theme was successfully created.' }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theme_params
      params.require(:theme).permit(:color)
    end
end

kursach-master/app/helpers/themes_helper.rb
module ThemesHelper
end

kursach-master/app/views/themes/_form.html.erb
<%= form_for(@theme) do |f| %>
  <% if @theme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
      <% @theme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

kursach-master/app/views/themes/edit.html.erb
<h1>Editing Theme</h1>

<%= render 'form' %>

<%= link_to 'Show', @theme %> |
<%= link_to 'Back', themes_path %>

kursach-master/app/views/themes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Themes</h1>

<table>
  <thead>
    <tr>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @themes.each do |theme| %>
      <tr>
        <td><%= theme.color %></td>
        <td><%= link_to 'Show', theme %></td>
        <td><%= link_to 'Edit', edit_theme_path(theme) %></td>
        <td><%= link_to 'Destroy', theme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theme', new_theme_path %>

kursach-master/app/views/themes/new.html.erb
<h1>New Theme</h1>

<%= render 'form' %>

<%= link_to 'Back', themes_path %>

kursach-master/app/views/themes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Color:</strong>
  <%= @theme.color %>
</p>

<%= link_to 'Edit', edit_theme_path(@theme) %> |
<%= link_to 'Back', themes_path %>